# Generated by Django 4.1.7 on 2024-12-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="priviledge",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Regular User", "Regular User")],
                default="Regular User",
                max_length=100,
            ),
        ),
    ]
